// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UI.Data;

#nullable disable

namespace UI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251105115011_stringifyforRole")]
    partial class stringifyforRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UI.Models.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PagesCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "آلبر کامو",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "images\\books\\the-stranger.jpg",
                            PagesCount = 120,
                            Price = 450000m,
                            Title = "غریبه"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "لئو تولستوی",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "images\\books\\war-and-peace.jpg",
                            PagesCount = 1225,
                            Price = 600000m,
                            Title = "جنگ و صلح"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "جبران خلیل جبران",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "images\\books\\the-prophet.jpg",
                            PagesCount = 100,
                            Price = 380000m,
                            Title = "پیامبر"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "آنتوان دو سنت‌اگزوپری",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "images\\books\\The-Little-Prince.jpg",
                            PagesCount = 90,
                            Price = 250000m,
                            Title = "شازده کوچولو"
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "استیون هاوکینگ",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "images\\books\\THE-THEORY-OF-EVERYTHING.jpg",
                            PagesCount = 160,
                            Price = 500000m,
                            Title = "نظریه‌ی همه‌چیز"
                        });
                });

            modelBuilder.Entity("UI.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BriefDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BriefDescription = "معاصر، کلاسیک",
                            ImageUrl = "/images/categories/books-icon.png",
                            Name = "رمان و داستان"
                        },
                        new
                        {
                            Id = 2,
                            BriefDescription = "غرب و شرق",
                            ImageUrl = "/images/categories/brain-icon.png",
                            Name = "فلسفه و منطق"
                        },
                        new
                        {
                            Id = 3,
                            BriefDescription = "فناوری و تاریخ",
                            ImageUrl = "/images/categories/microscope-icon.png",
                            Name = "علمی و تاریخی"
                        },
                        new
                        {
                            Id = 4,
                            BriefDescription = "داستان‌های مصور",
                            ImageUrl = "/images/categories/child-icon.png",
                            Name = "کودک و نوجوان"
                        },
                        new
                        {
                            Id = 5,
                            BriefDescription = "طراحی و نقاشی",
                            ImageUrl = "/images/categories/art-icon.png",
                            Name = "هنر و معماری"
                        });
                });

            modelBuilder.Entity("UI.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "امیر",
                            Lastname = "امیری",
                            Password = "admin1",
                            Role = "Admin",
                            Username = "admin1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "رضا",
                            Lastname = "قربانی",
                            Password = "admin2",
                            Role = "Admin",
                            Username = "admin2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "عماد",
                            Lastname = "گرامی",
                            Password = "emad",
                            Role = "Customer",
                            Username = "emad"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "علی",
                            Lastname = "علیپور",
                            Password = "ali",
                            Role = "Customer",
                            Username = "ali"
                        });
                });

            modelBuilder.Entity("UI.Models.Entities.Book", b =>
                {
                    b.HasOne("UI.Models.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UI.Models.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
